version: '3.8'

services:
  imagecleaner:
    build: .
    container_name: imagecleaner_app
    ports:
      - "80:8080" # Маппинг: порт_на_хосте:порт_в_контейнере
    env_file:
      - .env
    restart: always